---
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # This is updated manually from a fork at https://github.com/andrewkroh/beats/tree/hack/break-unix-dep.
      - dependency-name: github.com/elastic/beats/v7
    open-pull-requests-limit: 2
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
