name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: add GOPATH/bin to PATH
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: check fmt
        shell: bash
        run: |
          make fmt
          git diff-index --quiet HEAD

      - name: check go.mod
        shell: bash
        run: |
          go mod tidy
          git diff-index --quiet HEAD

      - name: build
        run: VERSION=${{ github.sha }} make build

      - name: go test
        run: go test ./...

      - name: publish gh-pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git config --local user.email "$(git log --format='%ae' HEAD^!)"
          git config --local user.name "$(git log --format='%an' HEAD^!)"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          VERSION=${{ github.sha }} make gh-pages
