name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: add GOPATH/bin to PATH
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: check fmt
        shell: bash
        run: |
          make fmt
          git diff-index --quiet HEAD

      - name: check go.mod
        shell: bash
        run: |
          go mod tidy
          git diff-index --quiet HEAD

      - name: go test
        run: go test ./...

      - name: build
        run: VERSION=${{ github.sha }} make build

      - name: publish gh-pages
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          VERSION=${{ github.sha }} make gh-pages
