name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: set release version
        id: release_version
        run: echo "name=tag::${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: add GOPATH/bin to PATH
        run: |
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - uses: actions/setup-node@v6
        with:
          node-version: '12'

      - name: install gox
        run: go install github.com/mitchellh/gox@latest

      - name: build
        run: VERSION=${{ steps.release_version.outputs.tag }} make build

      - name: cross build
        shell: bash
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          mkdir -p build/bin
          gox -ldflags '-X main.version=${{ steps.release_version.outputs.tag }}' \
              -output='build/bin/{{.Dir}}-{{.OS}}-{{.Arch}}' \
              -os='windows linux darwin freebsd' \
              -arch='amd64 arm64'

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: build/bin/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
